<?php

namespace Database\Seeders;

use App\Models\Badge;
use Illuminate\Database\Seeder;

class BadgeSeeder extends Seeder
{
    public function run(): void
    {
        $badges = [
            [
                'slug' => 'first-spark',
                'title' => 'The First Spark',
                'title_hi' => 'पहली चिंगारी',
                'description' => 'Complete your very first habit check-in.',
                'description_hi' => 'अपना पहला आदत चेक-इन पूरा करें।',
                'tier' => 'bronze',
                'icon' => 'spark',
                'unlock_criteria_json' => ['action' => 'first_checkin'],
            ],
            [
                'slug' => '3-day-momentum',
                'title' => '3-Day Momentum',
                'title_hi' => '3-दिवसीय गतिशीलता',
                'description' => 'Maintain an unbroken 3-day active streak.',
                'description_hi' => 'लगातार 3 दिन सक्रिय स्ट्रीक बनाए रखें।',
                'tier' => 'bronze',
                'icon' => 'streak_3',
                'unlock_criteria_json' => ['streak' => 3],
            ],
            [
                'slug' => '7-days-iron',
                'title' => '7 Days of Iron',
                'title_hi' => '7 दिन का लौह संकल्प',
                'description' => 'Maintain a continuous 7-day streak.',
                'description_hi' => 'लगातार 7 दिन तक अपनी स्ट्रीक बनाए रखें।',
                'tier' => 'bronze',
                'icon' => 'iron_7',
                'unlock_criteria_json' => ['streak' => 7],
            ],
            [
                'slug' => 'fortnight-warrior',
                'title' => 'Fortnight Warrior',
                'title_hi' => 'पक्षीय योद्धा (14 दिन)',
                'description' => 'Complete 14 continuous days without missing.',
                'description_hi' => 'बिना चूके लगातार 14 दिन पूरे करें।',
                'tier' => 'silver',
                'icon' => 'warrior_14',
                'unlock_criteria_json' => ['streak' => 14],
            ],
            [
                'slug' => '21-day-habit-master',
                'title' => '21-Day Habit Master',
                'title_hi' => '21-दिवसीय आदत उस्ताद',
                'description' => 'Complete the 21-Day Habit Builder challenge.',
                'description_hi' => '21-दिवसीय आदत निर्माता चुनौती पूरी करें।',
                'tier' => 'silver',
                'icon' => 'habit_master',
                'unlock_criteria_json' => ['challenge_slug' => '21-day-habit-builder'],
            ],
            [
                'slug' => 'one-month-club',
                'title' => 'One Month Club',
                'title_hi' => 'एक माह क्लब',
                'description' => 'Reach a 30-day continuous streak.',
                'description_hi' => 'लगातार 30 दिनों की स्ट्रीक तक पहुँचें।',
                'tier' => 'silver',
                'icon' => 'month_30',
                'unlock_criteria_json' => ['streak' => 30],
            ],
            [
                'slug' => '60-day-titan',
                'title' => '60-Day Titan',
                'title_hi' => '60-दिवसीय महाबली',
                'description' => 'Reach a 60-day continuous streak.',
                'description_hi' => 'लगातार 60 दिनों की स्ट्रीक पूरी करें।',
                'tier' => 'gold',
                'icon' => 'titan_60',
                'unlock_criteria_json' => ['streak' => 60],
            ],
            [
                'slug' => '90-day-rebirth',
                'title' => 'The 90-Day Rebirth',
                'title_hi' => '90-दिवसीय नवजागरण',
                'description' => 'Successfully complete the 90-Day Transformation.',
                'description_hi' => '90-दिवसीय रूपांतरण को सफलतापूर्वक पूरा करें।',
                'tier' => 'platinum',
                'icon' => 'rebirth_90',
                'unlock_criteria_json' => ['challenge_slug' => '90-day-transformation'],
            ],
            [
                'slug' => 'the-centurion',
                'title' => 'The Centurion',
                'title_hi' => 'शतनायक (100 दिन)',
                'description' => 'Reach a 100-day active streak.',
                'description_hi' => '100 दिनों की सक्रिय स्ट्रीक का मील का पत्थर पार करें।',
                'tier' => 'platinum',
                'icon' => 'centurion_100',
                'unlock_criteria_json' => ['streak' => 100],
            ],
            [
                'slug' => 'year-of-discipline',
                'title' => 'Year of Discipline',
                'title_hi' => 'अनुशासन का एक वर्ष',
                'description' => 'Reach 365 days of unbroken habit adherence.',
                'description_hi' => 'अटूट अभ्यास के 365 दिन पूरे करें।',
                'tier' => 'diamond',
                'icon' => 'year_365',
                'unlock_criteria_json' => ['streak' => 365],
            ],
            [
                'slug' => 'dawn-patrol',
                'title' => 'Dawn Patrol',
                'title_hi' => 'उषा रक्षक',
                'description' => 'Complete morning wake-up task before 06:00 AM (7 times).',
                'description_hi' => 'सुबह 6:00 बजे से पहले 7 बार जागने का कार्य पूरा करें।',
                'tier' => 'bronze',
                'icon' => 'dawn_sun',
                'unlock_criteria_json' => ['dawn_count' => 7],
            ],
            [
                'slug' => 'early-bird-master',
                'title' => 'Early Bird Master',
                'title_hi' => 'प्रातःकाल शिरोमणि',
                'description' => 'Check in pre-dawn wake-up for 21 consecutive days.',
                'description_hi' => 'लगातार 21 दिनों तक सुबह का कार्य पूरा करें।',
                'tier' => 'silver',
                'icon' => 'early_bird',
                'unlock_criteria_json' => ['early_bird_streak' => 21],
            ],
            [
                'slug' => 'ice-in-the-veins',
                'title' => 'Ice In The Veins',
                'title_hi' => 'शीत योद्धा',
                'description' => 'Complete 14 consecutive cold shower shocks.',
                'description_hi' => 'लगातार 14 दिन ठंडे पानी से स्नान का कार्य पूरा करें।',
                'tier' => 'silver',
                'icon' => 'cold_ice',
                'unlock_criteria_json' => ['cold_showers' => 14],
            ],
            [
                'slug' => 'deep-diver',
                'title' => 'Deep Diver',
                'title_hi' => 'गहन गोताखोर (10 घंटे)',
                'description' => 'Complete 10 hours of logged native focus sessions.',
                'description_hi' => '10 घंटे का गहरा ध्यान/कार्य सत्र पूरा करें।',
                'tier' => 'bronze',
                'icon' => 'focus_10',
                'unlock_criteria_json' => ['focus_hours' => 10],
            ],
            [
                'slug' => 'flow-state-virtuoso',
                'title' => 'Flow State Virtuoso',
                'title_hi' => 'प्रवाह उस्ताद (50 घंटे)',
                'description' => 'Log 50 hours of uninterrupted deep work.',
                'description_hi' => '50 घंटे का निर्बाध गहरा कार्य दर्ज करें।',
                'tier' => 'silver',
                'icon' => 'focus_50',
                'unlock_criteria_json' => ['focus_hours' => 50],
            ],
            [
                'slug' => 'deep-sanctuary',
                'title' => 'The Deep Sanctuary',
                'title_hi' => 'परम एकाग्रता (100 घंटे)',
                'description' => 'Log 100 hours of uninterrupted deep work.',
                'description_hi' => '100 घंटे का निर्बाध गहरा कार्य दर्ज करें।',
                'tier' => 'gold',
                'icon' => 'focus_100',
                'unlock_criteria_json' => ['focus_hours' => 100],
            ],
            [
                'slug' => 'dopamine-striker',
                'title' => 'Dopamine Striker',
                'title_hi' => 'डोपामिन प्रहारी',
                'description' => 'Block distracting apps for 7 consecutive days.',
                'description_hi' => 'लगातार 7 दिन तक ध्यान भटकाने वाले ऐप्स को ब्लॉक रखें।',
                'tier' => 'bronze',
                'icon' => 'blocker_7',
                'unlock_criteria_json' => ['blocker_days' => 7],
            ],
            [
                'slug' => 'digital-minimalist',
                'title' => 'Digital Minimalist',
                'title_hi' => 'डिजिटल संन्यासी',
                'description' => 'Maintain under 2 hours daily screen time for 14 days.',
                'description_hi' => '14 दिनों तक दैनिक स्क्रीन समय 2 घंटे से कम रखें।',
                'tier' => 'silver',
                'icon' => 'minimalist',
                'unlock_criteria_json' => ['low_screen_days' => 14],
            ],
            [
                'slug' => 'blocker-fortress',
                'title' => 'Blocker Fortress',
                'title_hi' => 'अभेद्य दुर्ग',
                'description' => 'Resist 50 emergency unlock temptations.',
                'description_hi' => '50 बार अनलॉक करने के प्रलोभन को रोकें।',
                'tier' => 'gold',
                'icon' => 'fortress',
                'unlock_criteria_json' => ['unlock_resisted' => 50],
            ],
            [
                'slug' => 'hydration-king',
                'title' => 'Hydration King',
                'title_hi' => 'जल नायक',
                'description' => 'Hit 3.5L water goal for 21 consecutive days.',
                'description_hi' => 'लगातार 21 दिनों तक 3.5 लीटर पानी का लक्ष्य पूरा करें।',
                'tier' => 'silver',
                'icon' => 'water_drop',
                'unlock_criteria_json' => ['water_streak' => 21],
            ],
            [
                'slug' => 'sunlight-primed',
                'title' => 'Sunlight Primed',
                'title_hi' => 'सौर ऊर्जा संपन्न',
                'description' => 'Log 15m outdoor morning sunlight for 14 days.',
                'description_hi' => '14 दिनों तक 15 मिनट सुबह की धूप का कार्य पूरा करें।',
                'tier' => 'bronze',
                'icon' => 'sunlight',
                'unlock_criteria_json' => ['sunlight_days' => 14],
            ],
            [
                'slug' => 'stoic-scribe',
                'title' => 'Stoic Scribe',
                'title_hi' => 'धैर्यवान लेखक',
                'description' => 'Write 7 consecutive evening journal entries.',
                'description_hi' => 'लगातार 7 शाम जर्नल प्रविष्टियां लिखें।',
                'tier' => 'bronze',
                'icon' => 'journal_7',
                'unlock_criteria_json' => ['journal_streak' => 7],
            ],
            [
                'slug' => 'master-of-reflection',
                'title' => 'Master of Reflection',
                'title_hi' => 'आत्मचिंतन शिरोमणि',
                'description' => 'Write 30 continuous evening journal reflections.',
                'description_hi' => 'लगातार 30 दिनों तक दैनिक आत्मचिंतन लिखें।',
                'tier' => 'silver',
                'icon' => 'journal_30',
                'unlock_criteria_json' => ['journal_streak' => 30],
            ],
            [
                'slug' => 'the-phoenix',
                'title' => 'The Phoenix',
                'title_hi' => 'फीनिक्स (सफल वापसी)',
                'description' => 'Successfully return via Comeback Mode after missing days.',
                'description_hi' => 'दिन छूटने के बाद कमबैक मोड से सफलतापूर्वक वापसी करें।',
                'tier' => 'bronze',
                'icon' => 'phoenix_fire',
                'unlock_criteria_json' => ['action' => 'comeback_success'],
            ],
            [
                'slug' => 'shield-bearer',
                'title' => 'Shield Bearer',
                'title_hi' => 'ढाल धारक (फ्रीज रक्षक)',
                'description' => 'Save an active streak using an earned Streak Freeze.',
                'description_hi' => 'स्ट्रीक फ्रीज का उपयोग करके अपनी स्ट्रीक सुरक्षित करें।',
                'tier' => 'bronze',
                'icon' => 'freeze_shield',
                'unlock_criteria_json' => ['action' => 'freeze_used'],
            ],
            [
                'slug' => 'summer-arc-victor',
                'title' => 'Summer Arc Victor',
                'title_hi' => 'समर आर्क विजेता',
                'description' => 'Complete the full 60-Day Summer Arc.',
                'description_hi' => 'पूरा 60-दिवसीय समर आर्क सफलतापूर्वक संपन्न करें।',
                'tier' => 'gold',
                'icon' => 'summer_victor',
                'unlock_criteria_json' => ['challenge_slug' => 'summer-arc'],
            ],
            [
                'slug' => 'winter-arc-victor',
                'title' => 'Winter Arc Victor',
                'title_hi' => 'विंटर आर्क विजेता',
                'description' => 'Complete the full 75-Day Winter Arc (Monk Mode).',
                'description_hi' => 'कठोर 75-दिवसीय विंटर आर्क (मोंक मोड) संपन्न करें।',
                'tier' => 'platinum',
                'icon' => 'winter_victor',
                'unlock_criteria_json' => ['challenge_slug' => 'winter-arc'],
            ],
            [
                'slug' => 'polymath',
                'title' => 'Polymath',
                'title_hi' => 'बहुमुखी साधक',
                'description' => 'Complete 3 different structured challenge arcs.',
                'description_hi' => '3 अलग-अलग संरचित आर्क सफलतापूर्वक पूरे करें।',
                'tier' => 'gold',
                'icon' => 'polymath',
                'unlock_criteria_json' => ['completed_arcs_count' => 3],
            ],
            [
                'slug' => 'custom-architect',
                'title' => 'Custom Architect',
                'title_hi' => 'स्वतंत्र शिल्पी',
                'description' => 'Create and complete a custom 30+ day arc.',
                'description_hi' => 'अपना खुद का 30+ दिनों का कस्टम आर्क बनाएं और पूरा करें।',
                'tier' => 'silver',
                'icon' => 'custom_arch',
                'unlock_criteria_json' => ['action' => 'custom_arc_complete'],
            ],
            [
                'slug' => 'the-unbreakable',
                'title' => 'The Unbreakable',
                'title_hi' => 'अजेय (The Unbreakable)',
                'description' => 'Attain Level 50 and forge an indomitable will.',
                'description_hi' => 'स्तर 50 प्राप्त करें और अटूट इच्छाशक्ति सिद्ध करें।',
                'tier' => 'diamond',
                'icon' => 'crown_diamond',
                'unlock_criteria_json' => ['level' => 50],
            ],
        ];

        foreach ($badges as $badgeData) {
            Badge::updateOrCreate(
                ['slug' => $badgeData['slug']],
                $badgeData
            );
        }
    }
}
